name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.2

    - name: Setup gotestsum
      uses: autero1/action-gotestsum@v1.0.0
      with:
        gotestsum_version: 1.6.2

    - name: Test
      run: gotestsum --format short-verbose -- -race -timeout=20m -coverprofile=coverage.txt -covermode=atomic ./...
